# 2부 코딩 수학 기초

## 1장 불리언 자료형과 비교 연산자

In [1]:
a = 5
print(a > 10)
type(a<10)

False


bool

`for` 반복문에서 사용하는 'in' 연산자도 불리언 값을 반환한다.

* 주의: 모든 연산자는 함수이다. 따라서 모두 반환값이 존재한다.

In [2]:
a = 'apple'
b = ['tomato', 'orange', 'strawberry', 'apple']
print(a in b)
type(a in b)

True


bool

In [3]:
for i in [1,2,3,4,5]: 
    if i > 3:         
        print(i)      

4
5


In [4]:
if True:
    print('1')

1


In [5]:
if False:
    print('1')

### 비교 연산자

변수 선언문은 어떤 값을 의미하지 않음.

In [6]:
a = 3
print(a = 3)

TypeError: 'a' is an invalid keyword argument for this function

두 값의 동일성/비동일성 여부는 `==`/`!=` 연산자 사용

In [7]:
print(a == 3)
print(a == 4)

print(a != 3)
print(a != 4)

True
False
False
True


In [8]:
def odd_or_even(n):
    if n % 2 == 0:
        print ('{}는 짝수이다'.format(n))
        k = 'even'
    elif n %2 != 0:
        print ('{}는 홀수이다'.format(n))
        k = 'odd'
    return n
print (odd_or_even(9))
print (odd_or_even(4))

9는 홀수이다
9
4는 짝수이다
4


## 2장 사칙연산

### 정수와 소수 사칙연산

In [18]:
print(3 + 5)
print(38 - 27)
print(3 * 5)  
print(8 / 2)  
print(type(8 / 2))

8
11
15
4.0
<class 'float'>


In [20]:
print(8 % 2)   # 나머지 구하기
print(7 / 2)   # 나누기
print(7 % 2)   # 나머지 구하기
print(7 // 2)  # 몫 구하기

0
3.5
1
3


### 거듭제곱(지수승)

In [21]:
print(2**3)
print(3**2)
print(100**2)

8
9
10000


괄호에 주의할 것

In [22]:
print((-2)**2)
print(-2 **2)

4
-4


### 반올림 함수: `round()`

In [31]:
print(round(3.2))
print(round(3.7))
print(round(3.5))

3
4
4


`round()` 함수의 리턴값은 정수 자료형이다.

In [34]:
print(type(round(3.2)))

<class 'int'>


## `math` 모듈 소개

* 지금까지는 파이썬의 기본패키지만 사용하였음.
* 하지만 보다 전문적인 프로그래밍을 위해서는 추가 모듈과 패키지가 요구됨.
* 여기서는 `math` 라는 모듈을 임포트(`import`, 추가 장착)하여 사용할 것임.
    * `math` 모듈 안에는 `sin`, `cos` 등 다양한 수학 함수들이 정의되어 있다.
* 모듈
    * 우선은 함수들의 정의를 모아 놓은 파이썬 소스코드 파일이라고 생각하면 됨.
    * 일종의 추가 도구상자 역할을 한다.
    * 예를 들어, 아래 예제에서 사용되는 `sqrt()` 함수는 제곱근을 구해주는 함수인데
        `math` 모듈(상자)에 포함되어 있다, 즉, 이미 구현되어 있다.

### 거듭제곱근

모듈 임포트 방식은 보통 아래 모양을 갖는다.

```python
import math
```

In [47]:
import math

임포트된 모듈에 정의된 함수들은 모듈 이름과 함께 사용해야 한다. 
```python
모듈이름.함수이름(인자1,...,인자k)
```

In [48]:
print (math.sqrt(100))
print (math.sqrt(16))
print (math.sqrt(7))

# 제곱근은 음수에는 정의되어 있지 않다.
print (math.sqrt(-4))

10.0
4.0
2.6457513110645907


ValueError: math domain error

## 3장 `for` 반복문: `range()`와 `enumerate()` 활용

### `range()` 함수

* `range()` 함수의 반환값은 리스트 처럼 사용된다.
* 반환값의 자료형은 `range`라고 불린다.
* 우선은 `range`와 `list` 자료형을 동일한 방식으로 사용하도록 하자.

In [36]:
a  = range(5)
print(a)
print(type(a))

range(0, 5)
<class 'range'>


In [48]:
for i in range(5):
    print (i)

0
1
2
3
4


`range()` 함수의 인자들의 역할은 리스트 슬라이싱 기능과 동일하다. 

In [50]:
for i in range(0,9,2):
    print (i)

0
2
4
6
8


즉, `range(0,9,2)`는 `[0, 2, 4, 6, 8]`과 거의 동일한 기능을 수행한다.

In [38]:
for i in range(0,-9,-2):
    print (i)

0
-2
-4
-6
-8


In [39]:
a = 0
for i in range(0,101):
    a += i
print ('0부터 100까지 더한 값 : {}'.format(a))

0부터 100까지 더한 값 : 5050


In [41]:
a = 0
for i in range(0,101): 
    if i % 2 == 1:     
        a += i         
print ('0부터 100까지 홀수를 더한 값 : {}'.format(a))

0부터 100까지 홀수를 더한 값 : 2500


### `enumerate()` 함수

* 리스트를 입력 받아 리스트의 항목과 인덱스의 쌍으로 이루어진 순서쌍들의 리스트와 
거의 유사한 값을 생성한다.
* 반환값의 자료형은 `enumerate` 이다.

In [45]:
fruit = ['strawberry', 'grape', 'apple', 'mango', 'orange']
a = enumerate(fruit)
print(a)
print(list(a))

[(0, 'strawberry'), (1, 'grape'), (2, 'apple'), (3, 'mango'), (4, 'orange')]


리스트의 항목과 인덱스에 대한 정보를 함께 사용하고자 할 때 유용하다.

In [46]:
a = [0,1,2,3,4]
for idx, val in enumerate(fruit): 
    print (idx, val) 

0 strawberry
1 grape
2 apple
3 mango
4 orange


## Chapter 4 while 반복문 

In [58]:
a = 10
c = 0

while a > 0:  # a 가 0보다 클때까지
    c += a    # c에다가는 a를 더하고
    a -= 1    # a는 a-1의 숫자로 재정의한다. (조건에 변화를 주는 문장))
print (c)

55


In [59]:
a = 0
while a < 20:  # a가 20보다 작을때까지
    a += 1     # a에 1씩 더하고
    print (a)    # a를 출력하여라

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [60]:
a = True
n = 0
while a:
    n += 1
    print (n)
    if n == 10:
        a = False

1
2
3
4
5
6
7
8
9
10


## 5장 `numpy` 모듈 활용

### `numpy` 모듈 소개

* `numpy` 라는 수치계산 전용 모듈을 임포트(`import`, 추가 장착)하여 사용할 것임.
* 앞서 언급한 `math` 모듈보다 훨씬 다양하고 보다 효율적으로 작동하는 수학 함수들을 포함한다.

### 거듭제곱근

* `numpy` 모듈에서 `sqrt` 함수가 정의되어 있다.
* `numpy` 모듈은 관행적으로 `np` 약칭으로 임포트한다.

**주의:** 약칭을 이용하여 임포트한 모듈은 약칭으로만 사용해야 한다.

In [49]:
import numpy as np

In [51]:
print (np.sqrt(100))
print (np.sqrt(16))
print (np.sqrt(7))

# 제곱근은 음수에는 정의되어 있지 않다.
print (np.sqrt(-4))

10.0
4.0
2.6457513110645907
nan


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in sqrt
  


###  `numpy` 모듈의 `array` 자료형

* `numpy`와 같은 모듈이 추가되면 자료형도 확장되기도 한다. 
* `array` 자료형도 그중 하나이다.
    * 엄밀하게는 `ndarray`이지만 보통 넘파이 어레이라 부른다.
    * `list` 자료형과 매우 유사
    * 좀 더 다양한 기능을 제공한다.

리스트를 이용하여 어레이 생성 가능

**주의:** `print` 함수의 출력결과 모양이 다름.

In [55]:
a = [1,2,3,4,5]
b = np.array(a)

print(a)
print(type(a))
print(b)
print(type(b))

[1, 2, 3, 4, 5]
<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


인덱싱, 슬라이싱 기능은 리스트의 경우와 동일

In [53]:
print (b[0], b[-5])
print (b[1], b[-4])
print (b[4], b[-1])
print (b[1:3])
print (b[::2])

1 1
2 2
5 5
[2 3]
[1 3 5]


#### 리스트와 어레이의 차이점

* 리스트와 숫자의 연산 불가

In [56]:
a + 5

TypeError: can only concatenate list (not "int") to list

* 어레이와 숫자의 연산 가능

In [63]:
c = b + 5

print(b)
print(c)

print(a*2)
print(b*2)

print(b/4)
print(b**2)

print(np.sqrt(c))

[1 2 3 4 5]
[ 6  7  8  9 10]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]
[0.25 0.5  0.75 1.   1.25]
[ 1  4  9 16 25]
[2.44948974 2.64575131 2.82842712 3.         3.16227766]


### 어레이 사책연산: `np.multiply` 연산자

In [71]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.multiply(a,b)

array([ 4, 10, 18])

### 04 np.max, np.min : array의 최대값과 최소값 구하기

In [72]:
print (np.max(a))
print (np.min(b))

3
4


### 05 np.argmax, np.argmin으로 array의 최대값과 최소값의 index 구하기

In [73]:
print (np.argmax(a))
print (np.argmin(b))

2
0


### 06 random으로 numpy 난수 만들기 

In [74]:
np.random.randint(9)

6

In [75]:
np.random.randint(100, 130, size = 2)

array([110, 106])

#### Question 2.1

In [76]:
def lotto():
    number = []                               # lotto 6개 숫자를 넣을 공집합 number를 만들고
    for i in range(6):                        # 6번의 숫자만들기에서
        new_element = np.random.randint(1,46) # 1에서 45까지의 난수를 new_element로 지정하고
        if new_element not in number:         # new_element가 number의 element에 없으면
            number.append(new_element)        # number에다가 new_element를 추가하여라
    return number

In [77]:
lotto()

[28, 26, 21, 3, 23]

#### Question 2.2

In [10]:
def random95():
    a = 0
    number = []
    while a < 95:
        a = np.random.randint(1, 101)
        number.append(a)
    return number
print(random95())

[73, 76, 64, 65, 64, 44, 94, 74, 19, 45, 60, 92, 64, 70, 51, 70, 26, 87, 91, 73, 95]


#### Question 2.3

In [79]:
def intersection(a,b):
    c = []               
    for i in a:
        if i  in b:
            c.append(i)
    c.sort()
    return c

입력값으로 최소, 최대 범위를 정하고 (위 문제에서는 1, 31), 난수 생성갯수 (위 문제에서는 10)를 받는 코딩함수를 만들겠습니다.

In [80]:
def random_exclusive(low, high, how_many):
    number = []                             # 난수의 집합을 우선 공집합으로 만들고
    while how_many > 0:                     # n이 0보다 클때까지 
        a = np.random.randint(low,high)     # 1부터 30까지의 난수를 만들어 a로 놓은다음
        if a not in number:                 # a가 number에 없으면
            number.append(a)                # number에 a를 추가하고
        how_many -= 1                       # n을 1 줄여라
    return number

In [81]:
random_exclusive(1,31,10)

[1, 4, 30, 12, 18, 6, 21, 27]

위 처럼 1부터 30까지 10개의 난수가 만들어졌습니다.

자 이제 두쌍을 만들고 교집합을 만드는 코딩함수를 만들겠습니다.

In [82]:
def random_intersection(low, high, how_many):
    group_A = random_exclusive(low, high, how_many)
    group_B = random_exclusive(low, high, how_many)
    c = intersection(group_A, group_B)
    print ('그룹 A의 난수는 : {}'.format(group_A))
    print ('그룹 B의 난수는 : {}'.format(group_B))
    print ('그룹 A와 그룹 B의 교집합은 {}'.format(c))
    return c
random_intersection(1,31,10)

그룹 A의 난수는 : [1, 23, 6, 4, 22, 18, 13, 11, 17]
그룹 B의 난수는 : [11, 3, 22, 19, 15, 25, 5, 27, 30]
그룹 A와 그룹 B의 교집합은 [11, 22]


[11, 22]

## Chapter 6 자연수 

### 01 소수 알아보기

In [83]:
a = 17
a_prime = True                  # True는 '참'이라는 의미이며 초기값을 참으로 정의
for i in range(2,a):            # 2부터 자기자신 -1까지의 수에대해
    if a % i == 0:              # a를 i로 나눈 나머지가 0이면, 
        a_prime = False         # a_prime을 '거짓'의 의미인 False로 바꾸어라

if a_prime == True:
    print ('{}는 소수이다.'.format(a))  # 소수이다를 출력하라
else:
    print ('{}는 소수가 아니다.'.format(a))

17는 소수이다.


In [84]:
def is_prime(a):
    b = range(2, a)  #2부터 a-1까지의 list
    c = 0
    for i in b:    
        if a % i == 0:  
            c += 1   
    if c > 0:
        print ('{}는 소수가 아니다.'.format(a))
        d = False   
    else:
        print ('{}는 소수이다.'.format(a))      
        d = True
    return d

In [85]:
is_prime(31)

31는 소수이다.


True

In [86]:
is_prime(18)

18는 소수가 아니다.


False

In [87]:
is_prime(597)

597는 소수가 아니다.


False

In [88]:
is_prime(449)

449는 소수이다.


True

#### Question 2.4 

In [89]:
def is_prime2(a):
    b = range(2, a)  #2부터 a-1까지의 list
    c = 0
    for i in b:    
        if a % i == 0:  
            c += 1   
    if c > 0:
        d = False   
    else:
        d = True
    return d

In [90]:
a = range(1,101)              # 100 까지니 101로 지정
prime_numbers = []            # 소수 list를 공집합으로 우선 만들고
for i in a:                   # 1부터 100까지 중,
    c = is_prime2(i)          # i가 소수이면 c는 True, 아니면 False 생성
    if c == True:             # c가 True이면
        prime_numbers.append(i)  # b에다가 i를 추가하라
print (prime_numbers)

[1, 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


#### Question 2.5

In [91]:
a = range(2,1001)                   # 2부터 1000 까지 지정
prime_numbers = [1]                # 소수 list를 1부터 시작하는 list로 만들고
diff = 0                           # 소수와 그다음 소수까지의 차이를 우선 0으로 만들고

for i in a:                        # 2부터 1000까지 중,
    c = is_prime2(i)               # i가 소수이면 c는 True, 아니면 False 생성
    if c == True:                  # c가 True이면
        prime_numbers.append(i)    # b에다가 i를 추가하라
        if prime_numbers[-1] - prime_numbers[-2] > diff:
            diff = prime_numbers[-1] - prime_numbers[-2]
            max_diff_primes = [prime_numbers[-2], prime_numbers[-1]]

print ('소수사이 구간의 최대값 : {}'.format(diff))
print ('최대구간의 소수쌍 : {}'.format(max_diff_primes))

소수사이 구간의 최대값 : 20
최대구간의 소수쌍 : [887, 907]


### 02 소인수 찾기

In [92]:
a = 17
b = range(2,a)               # 2부터 23까지의 수열을 만들고
primes = []                  # 소인수들로 이루어진 list를 만들텐데 우선 공집합으로 시작
for i in b:                  # 2부터 23까지 자연수에 대해 i로 놓고
    while a % i == 0:        # a를 로 나누어서 나머지가 0이면
        primes.append(i)     # c에 i를 추가하고
        a /= i               # a를 i로 나눈다음
                             # 이 과정을 반복해라

if primes == []:             # 만약 아무것도 나누어지지 않으면 
    primes.append(a)         # 소인수는 그 수 자체
    
primes        

[17]

In [93]:
def prime_factorization(a):
    b = range(2,a)
    primes = []
    for i in b:   # b의 요소인 i에 대해
        while a % i == 0: # a를 로 나누어서 나머지가 0이면
            primes.append(i) # c에 i를 추가하고
            a /= i   # a를 i로 나눈다음
    if primes == []:
        primes.append(a)
    return primes

In [94]:
print (prime_factorization(128))
print (prime_factorization(497))
print (prime_factorization(10135867))
print (prime_factorization(17))

[2, 2, 2, 2, 2, 2, 2]
[7, 71]
[7, 1447981]
[17]


### 03 약수 구하기

In [95]:
a = 24
b = range(1, 24)            # 1부터 23까지 자연수의 집합
factors = []                # 약수 list를 공집합으로 만들어놓고
for i in b:                 # b의 원소 i에 대해
    if a % i == 0:          # 24가 i로 나눈 나머지가 0이면
        factors.append(i)   # 약수집합에 i를 추가하여라
factors.append(a)           # 자기자신인 24를 추가하여라
print (factors)

[1, 2, 3, 4, 6, 8, 12, 24]


In [96]:
def factorization(a):
    b = range(1, a)   
    factors = []
    for i in b:
        if a % i == 0:
            factors.append(i)
    factors.append(a)
    return factors

In [97]:
print (factorization(36))
print (factorization(148))

[1, 2, 3, 4, 6, 9, 12, 18, 36]
[1, 2, 4, 37, 74, 148]


### 04 최대공약수, 최소공배수 구하기

In [98]:
def intersection(a,b):
    c = []
    for i in a:
        if i  in b:
            c.append(i)
    return c

In [99]:
def greatest_common_factor(a, b, show = False):  
    c = factorization(a)         # a의 약수를 구해 c 라는 list에 저장한다. 
    d = factorization(b)         # b의 약수를 구해 d 라는 list에 저장한다. 
    if show:                     # show 가 true이면
        print (c)                # a의 약수인 c를 출력하고
        print (d)                # b의 약수인 d를 출력하고
    e = intersection(c,d)        # c와 d의 교집합을 구한다.
    return max(e)                # 최대값을 return 한다.

In [100]:
a = 36
b = 96
greatest_common_factor(a,b)  

12

In [101]:
greatest_common_factor(a,b, show = True)  

[1, 2, 3, 4, 6, 9, 12, 18, 36]
[1, 2, 3, 4, 6, 8, 12, 16, 24, 32, 48, 96]


12

In [102]:
def sum_abc(a,b,c = 100):
    return a + b + c

In [103]:
sum_abc(1,2,3)

6

In [104]:
sum_abc(1,2)

103

In [105]:
print (prime_factorization(36))
print (prime_factorization(96))

[2, 2, 3, 3]
[2, 2, 2, 2, 2, 3]


In [106]:
def least_common_multiple(a, b):
    c = prime_factorization(a)  # a의 소인수를 구해 c 라는 list에 저장한다. 
    d = prime_factorization(b)  # b의 소인수를 구해 d 라는 list에 저장한다. 
    for i in c:            
        if i in d:              # c와 d의 공통원소이면
            d.remove(i)         # 1개만 취한다.
    e = c + d                   # a, b의 소인수들의 합집합인 소인수분대를 구한다. (공통된것은 1번만 계산)
    f = 1
    for i in e:     # e의 모든 원소에 대해
        f *= i      # f에다가 계속 곱해라
    return f

In [107]:
print (least_common_multiple(36,96))
print (least_common_multiple(4,7))

288
28


### 05 십진수 나타내기

In [108]:
a = 325
digit_10 = []
while a // 10 != 0:       # a를 10으로 나눠서 몫이 0이 아닐때까지
    e = a % 10            # e는 325를 10으로 나눈 나머지인 5
    digit_10.append(e)    # 5를 d에 추가한다.
    a //= 10              # 325를 10으로 나눈 몫 32를 새로운 a로 정의
                          # 위 과정을 32에 대해서 하고, 또 3에 대해서 한다.
digit_10.append(a)        # 3을 10으로 나눈 나머지인 3을 최종 추가해준다. 
print (digit_10)
digit_10.reverse()        # 순서를 거꾸로 하기
print (digit_10)

[5, 2, 3]
[3, 2, 5]


In [109]:
def digit_expand(a, n):   # n은 진수를 의미합니다. 10진수면 n에 10을 넣으면 됩니다.
    digit_10 = []
    while a // n != 0: 
        e = a % n  
        digit_10.append(e)
        a //= n 

    digit_10.append(a)
    digit_10.reverse()
    
    return digit_10

In [110]:
a = digit_expand(1732, 10)
a

[1, 7, 3, 2]

### 06 이진법 나타내기

In [111]:
a = digit_expand(11, 2)
a

[1, 0, 1, 1]

In [112]:
print (digit_expand(1732,2))

[1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0]


In [113]:
print (digit_expand(1732,7))
print (digit_expand(1732,9))
print (digit_expand(1732,16))

[5, 0, 2, 3]
[2, 3, 3, 4]
[6, 12, 4]


### 07 진법 변형하여 나타내기

In [114]:
def Number_system_change(number, n, m):
##################################
# number : 변형하려는 숫자
# n : 현재의 진법
# m : 미래의 진법
# number의 각 숫자가 n보다 크거나 같으면 error
##################################
    num_str = str(number)  # 325
    len_num = len(num_str) # 3
    
    # 우선 10진법으로 바꾸기
    number_10 = 0
    for i, num in enumerate(num_str):     # (0,'3'), (1,'2'), (2,'5') 형태의 (i,num)이 됨
        num_int = int(num)                # 문자형'3'을 정수형 3으로 변형
        if num_int >= n:                  # 2진법에 2보다 큰 숫자가 오면 안되므로 이 조건문을 써야함
            print ('{}는 {}보다 크거나 같으니 {}진법의 수가 아니다.'.format(num_int, n, n))
            break                         # 이렇게 잘못하면 break로 if와 for 반복을 끝냄
        else:
            number_10 += num_int*n**(len_num-i-1)  #(3 x 6**2) + (2 x 6) + (5 x 1) 하는 과정임

    # 10진법을 m진법으로 바꾸기
    number_m = digit_expand(number_10, m)  
    return number_m

In [115]:
Number_system_change(325,10,7)  # 10진수인 325를 7진수로 표기하여라

[6, 4, 3]

In [116]:
Number_system_change(5023,7,9)

[2, 3, 3, 4]

### 08 클래스로 임의의 자연수 문제 만들기

In [117]:
import numpy as np
class Natural_number:
    def question(self):
        self.select = np.random.randint(5)  
        self.n1 = np.random.randint(100)
        self.n2 = np.random.randint(100)     
        self.n3 = np.random.randint(low = 2, high = 10)
        self.n4 = np.random.randint(low = 2, high = 30)
        
        if self.select == 0:
            print ('{}가 소수인지 판별하고, 소수가 아니면, 약수를 구해라'.format(self.n1))
        elif self.select ==1:
            print ('{}와 {}의 최대공약수를 구하여라'.format(self.n1, self.n2))
        elif self.select ==2: 
            print ('{}와 {}의 최소공배수를 구하여라'.format(self.n3, self.n4))
        elif self.select == 3:
            print ('{}를 2진법으로 나타내어라'.format(self.n1))
        elif self.select == 4:
            self.n4_2 = digit_expand(self.n4, 2)
#            print '2진수 %i를 10진법으로 나타내어라' %self.n4
            print ('2진수 [{}]를 10진법으로 나타내어라'.format(', '.join(map(str, self.n4_2))))
            
    def answer(self):
        if self.select == 0:
            if is_prime2(self.n1):
                print ('{} 는 소수이다.'.format(self.n1))
            else:
                print (factorization(self.n1))
        elif self.select == 1:
            print (greatest_common_factor(self.n1,self.n2, show = True))
        elif self.select == 2:
            print (least_common_multiple(self.n3, self.n4))
        elif self.select == 3:
            print (digit_expand(self.n1, 2))
        elif self.select == 4:
            print (digit_expand(self.n4, 10))

In [118]:
q1 = Natural_number()
q1.question()

2진수 [1, 0, 1]를 10진법으로 나타내어라


In [119]:
q1.answer()

[5]


In [120]:
q2 = Natural_number()
q2.question()

7가 소수인지 판별하고, 소수가 아니면, 약수를 구해라


In [121]:
q2.answer()

7 는 소수이다.


#### Question 2.6

In [122]:
a = [1,2,3,4]
number = ''
for i in range(len(a)):
    number = number + str(a[i])
number = int(number)
number

1234

In [123]:
a = [1,2,3,4]
def list_to_number(a):
    number = ''
    for i in range(len(a)):
        number = number + str(a[i])
    number = int(number)
    return number

In [124]:
list_to_number([3,2,4,6,7,4,2,69])

324674269

In [125]:
str(a[0])

'1'

In [126]:
number = ''
number + str(3)

'3'

#### Question 2.7

In [127]:
def pibonacci(n):
    pib = [1,2]
    for i in range(2,n):
        pib.append(pib[-1]+pib[-2])
    return pib[-1]

In [128]:
pibonacci(5)

8

#### Question 2.8

In [129]:
n = 1
for i in range(5):
    temp = np.random.randint(1,10)
    print (temp)
    n *= temp
n

7
5
8
6
7


11760

#### Question 2.9

In [130]:
a, b = np.random.randint(10,100,size = 2)
print (a,b)
least_common_multiple(a, b)

54 69


1242

#### Question 2.10

In [131]:
factorization(210)

[1, 2, 3, 5, 6, 7, 10, 14, 15, 21, 30, 35, 42, 70, 105, 210]

In [132]:
factors = factorization(210)
for i in factors:
    if greatest_common_factor(i, 42) == 6:
        print ('그 수는 {}'.format(i))

그 수는 6
그 수는 30


#### Question 2.11

In [133]:
factorization(60)

[1, 2, 3, 4, 5, 6, 10, 12, 15, 20, 30, 60]

In [134]:
factors = factorization(60)[6:]
factors

[10, 12, 15, 20, 30, 60]

In [135]:
for i in factors:
    for j in factors:
        if j != i:
            if greatest_common_factor(i, j) == 6:
                if least_common_multiple(i, j) == 60:
                    print ('그 수는 {}와 {}'.format(i,j))

그 수는 12와 30
그 수는 30와 12


#### Question 2.12

In [136]:
factors = factorization(60)
print (factors)

[1, 2, 3, 4, 5, 6, 10, 12, 15, 20, 30, 60]


In [137]:
for i in factors:
    for j in factors:
        if i-j == 8:
            if greatest_common_factor(i, j) == 4:
                if least_common_multiple(i, j) == 60:
                    print ('그 수는 {}와 {}'.format(i,j))

그 수는 20와 12


#### Question 2.13

In [138]:
for i in range(100):
    if (i % 6 == 3) and (i % 8 == 5) and (i % 9 == 6):
        print (i)

69


#### Question 2.14

In [139]:
prime_factorization(48)

[2, 2, 2, 2, 3]

#### Question 2.15

In [140]:
greatest_common_factor(48,greatest_common_factor(60,72))

12

In [141]:
(48/12) * (72/12) * (60/12) 

120.0

#### Question 2.16

In [142]:
least_common_multiple(12,least_common_multiple(6,9))

36

In [143]:
(36/12) * (36/9) * (36/6)

72.0

#### Question 2.17

In [144]:
for i in range(2,100):
    if (i%4 == 1) and (i % 5 == 1) and (i % 6) == 1:
        print (i)

61


#### Question 2.18

In [145]:
a = Number_system_change(621, 7, 10)
b = Number_system_change(3213, 4, 10)
a = list_to_number(a)
b = list_to_number(b)
print (a)
print (b)
print ('{}개의 수가 있다.'.format(a-b))

309
231
78개의 수가 있다.


## Chapter 7 정수 

In [146]:
class Integer:
    def question(self):
        self.constant = np.random.randint(low = -10, high = 10, size = 2)
        self.pm = np.random.randint(5)
        self.exponent = np.random.randint(low = 2, high = 4)
        if self.pm == 0:
            print ('{} + {} = ?' .format(self.constant[0],  self.constant[1]))
        elif self.pm == 1:
            print ('{} - {} = ?' .format(self.constant[0],  self.constant[1]))
        elif self.pm == 2:
            print ('{} x {} = ?' .format(self.constant[0],  self.constant[1]))
        elif self.pm == 3:
            print ('{} / {} = ?' .format(self.constant[0],  self.constant[1]))
        else:
            print ('{}^{} = ?' .format(self.constant[0],  self.exponent))
            
    def answer(self):
        if self.pm == 0:
            return self.constant[0] + self.constant[1]
        elif self.pm == 1:
            return self.constant[0] - self.constant[1]
        elif self.pm == 2:
            return self.constant[0] * self.constant[1]
        elif self.pm == 3:
            return self.constant[0] / self.constant[1]
        else:
            return self.constant[0] ** self.exponent

In [147]:
q1 = Integer()
q1.question()

-10^3 = ?


In [148]:
q1.answer()

-1000

### 01 절대값 구하기

In [149]:
a = -5
np.abs(a)

5

### 02 덧셈 뺄셈 교환 법칙 및 결합 법칙 알아보기

In [150]:
print ((-2) + 7)
print (7+ (-2))

5
5


In [151]:
print (((-2)+(-3)) + +4)
print ((-2)+ ((-3) + +4))

-1
-1


### 03 계산하기

In [152]:
5 + (-3) * (-2)**2

-7

In [153]:
(3 + 2 * (5 - 7)) * 4 - 10

-14

In [154]:
(8 - (-5) * 2) * 2 -1

35

In [155]:
2 - (2 * ((-1)**2 + 4 / 2) -1)

-3.0

## Chapter 8 유리수와 무리수 

In [156]:
from fractions import Fraction  # fraction이라는 module에서 Fraction이라는 

In [157]:
print (Fraction(5/2))
print (Fraction(2.5))
print (Fraction(5,2))

5/2
5/2
5/2


In [158]:
Fraction(7,9).numerator

7

In [159]:
Fraction(7,9).denominator

9

In [160]:
Fraction(2,4)

Fraction(1, 2)

In [161]:
Fraction(1,4) * Fraction(4,7)

Fraction(1, 7)

In [162]:
Fraction(1,4) / Fraction(4,7)

Fraction(7, 16)

In [163]:
Fraction(1,4) + Fraction(4,7)

Fraction(23, 28)

In [164]:
Fraction(1,4) - Fraction(4,7)

Fraction(-9, 28)

제곱도 할 수 있습니다.

In [165]:
Fraction(1,4)**2

Fraction(1, 16)

In [166]:
a = Fraction(9, 16)
a = float(a)
np.sqrt(a)

0.75

### 01 임의의 유리수 문제 만들기

In [167]:
class Rational_number:
    def question(self):
        self.constant = np.random.randint(low = -10, high = 10, size = 4)
        self.pm = np.random.randint(4)
        if self.pm == 0:
            print ('({}/{}) + ({}/{}) = ?' .format(self.constant[0],self.constant[1],self.constant[2],self.constant[3]))
        elif self.pm == 1:
            print ('({}/{}) - ({}/{}) = ?' .format(self.constant[0],self.constant[1],self.constant[2],self.constant[3]))
        elif self.pm == 2:
            print ('({}/{}) * ({}/{}) = ?' .format(self.constant[0],self.constant[1],self.constant[2],self.constant[3]))
        else:
            print ('({}/{}) / ({}/{}) = ?' .format(self.constant[0],self.constant[1],self.constant[2],self.constant[3]))
        
    def answer(self):
        if self.pm == 0:
            return Fraction(self.constant[0],self.constant[1]) + Fraction(self.constant[2],self.constant[3])
        elif self.pm == 1:
            return Fraction(self.constant[0],self.constant[1]) - Fraction(self.constant[2],self.constant[3])
        elif self.pm == 2:
            return Fraction(self.constant[0],self.constant[1]) * Fraction(self.constant[2],self.constant[3])
        else:
            return Fraction(self.constant[0],self.constant[1]) / Fraction(self.constant[2],self.constant[3])

In [168]:
q1 = Rational_number()
q1.question()

(-8/7) + (6/7) = ?


In [169]:
q1.answer()

Fraction(-2, 7)

In [170]:
float(Fraction(1,7))

0.14285714285714285

In [171]:
round(float(Fraction(1,7)))

0

In [172]:
round(float(Fraction(1,7)),1)

0.1

In [173]:
round(float(Fraction(1,7)),6)

0.142857

### 02 분수를 유한 소수로 나타내기

In [8]:
def prime_factorization(a):
    b = range(2,a)
    primes = []
    for i in b:   # b의 요소인 i에 대해
        while a % i == 0: # a를 로 나누어서 나머지가 0이면
            primes.append(i) # c에 i를 추가하고
            a /= i   # a를 i로 나눈다음
    if primes == []:
        primes.append(a)
    return primes

0.25

In [19]:
a = Fraction(1,4)
prime_factorization(a.denominator)

[2, 2]

In [24]:
a = Fraction(7,9)

print (prime_factorization(a.denominator))
print (float(a))

[3, 3]
0.7777777777777778


#### Question 2.19 

In [51]:
def finite_OX(a,b):
    finite = True
    primes = prime_factorization(Fraction(a,b).denominator)
    for i in primes:
        if i != 2 and i != 5:    # i가 2가 아니고 5도 아니면
            finite = False       # finite은 거짓
    return finite

In [49]:
finite_OX(17,30)

False

In [52]:
finite_OX(12,15)

True

#### Question 2.20

In [57]:
x = range(80,91)

for i in x:
    if finite_OX(i,450):
        if Fraction(i,450).numerator == 9:
            y = Fraction(i,450).denominator
            print (i-y)

31


#### Question 2.21

In [62]:
number_of_finite = 0
for i in range(1,101):
    if finite_OX(1,i):
        number_of_finite += 1
print('유한소수 갯수는 : {}'.format(number_of_finite))

유한소수 갯수는 : 14


#### Question 2.22

In [63]:
a = range(1,10)
for i in a:
    if finite_OX(i,90):
        if Fraction(i,90).numerator == 1:
            b = Fraction(i,90).denominator
            print(i+b)

19


### 03 무리수 익히기

In [7]:
np.sqrt(3)

1.7320508075688772

In [6]:
np.pi

3.141592653589793

In [64]:
np.pi * np.sqrt(3)

5.4413980927026531

#### Question 2.23

In [76]:
prime_factorization(40)

[2, 2, 2, 5]

#### Question 2.24

In [86]:
a = [2,2,2,5]
new_number = []
for i in a:
    if i not in new_number:
        new_number.append(i)
print (new_number)

[2, 5]


In [90]:
how_many = []
for j in new_number:
    how_many.append(a.count(j))
print (how_many)

[3, 1]


In [129]:
min_n = []
for idx, val in enumerate(how_many):
    if val % 2 == 0:
        min_n.append(1)
    else:
        min_n.append(new_number[idx])
min_n

[2, 5]

In [130]:
min_n_multiply = 1
for i in min_n:
    min_n_multiply *= i
min_n_multiply

10

In [137]:
def min_n_for_rational(n):
    primes = prime_factorization(n)
    new_number = []
    for i in primes:
        if i not in new_number:
            new_number.append(i)
    print ('소인수분해 : {}'.format(primes))
    print ('소인수 : {}'.format(new_number))
    
    how_many = []
    for j in new_number:
        how_many.append(primes.count(j))
    print ('몇개씩 있나 : {}'.format(how_many))
    
    min_n = []
    for idx, val in enumerate(how_many):
        if val % 2 == 0:
            min_n.append(1)
        else:
            min_n.append(new_number[idx])
    min_n
    print ('얼마나 곱해야 하나 : {}'.format(min_n))
    
    min_n_multiply = 1
    for i in min_n:
        min_n_multiply *= i
    
    print ('{}에서 최소 {}을 곱하면 {}이고 이의 제곱근은 {}이다.'.format(n, min_n_multiply, n*min_n_multiply, np.sqrt(n*min_n_multiply)))

    return min_n_multiply

In [142]:
min_n_for_rational(104)

소인수분해 : [2, 2, 2, 13]
소인수 : [2, 13]
몇개씩 있나 : [3, 1]
얼마나 곱해야 하나 : [2, 13]
104에서 최소 26을 곱하면 2704이고 이의 제곱근은 52.0이다.


26

In [143]:
min_n_for_rational(105)

소인수분해 : [3, 5, 7]
소인수 : [3, 5, 7]
몇개씩 있나 : [1, 1, 1]
얼마나 곱해야 하나 : [3, 5, 7]
105에서 최소 105을 곱하면 11025이고 이의 제곱근은 105.0이다.


105