# 연립방정식 풀기

In [1]:
import numpy as np

## 리스트 조건제시법

In [2]:
a = [2*x for x in [3,5,6,8,9]]
a

[6, 10, 12, 16, 18]

In [3]:
b = [x % 7 for x in range(10,20)]
b

[3, 4, 5, 6, 0, 1, 2, 3, 4, 5]

if를 이용하여 조건을 달 수 있다.

In [4]:
a = [2*x for x in [3,5,6,8,9] if x % 2 == 0]
a

[12, 16]

#### 연습: 소수 구하기

In [5]:
def is_prime(a):
    b = range(2, a)
    for i in b:    
        if a % i == 0:  
            return False
    return True

In [6]:
d = [x**2 for x in range(1,50) if is_prime(x)]
d

[1, 4, 9, 25, 49, 121, 169, 289, 361, 529, 841, 961, 1369, 1681, 1849, 2209]

## 일차방정식 다루기

### `a * x + b = c`의 해 구하기

In [7]:
def linear_eq(a,b,c):
    if a == 0 and b == c:
        print('해는 모든 수')
    elif a == 0 and b != c:
        print('해 없음')
    else:
        return (c-b)/a

In [8]:
linear_eq(2,-3,5)

4.0

In [9]:
linear_eq(0,3,4)

해 없음


In [10]:
linear_eq(0,3,3)

해는 모든 수


## 1차 연립방정식 다루기

아래 1차 연립방정식을 풀어보자.

```
5*x + 2*y = 14
2*x +   y = 4
```
2번 식의 양변에 2를 곱한다.
```
5*x + 2*y = 14
4*x + 2*y = 8
```
1번식에서 2번식을 뺀다. 
양변을 똑같이 빼고 동일한 변수의 계수끼리 뺀다.
```
x = 6
```
이제 `y`값을 계산한다.
```
y = 8
```

In [11]:
a = np.array([5, 2, 14])
b = np.array([2, 1, 4])
c = b*2
c

array([4, 2, 8])

In [12]:
d = a - c
d

array([1, 0, 6])

In [13]:
x = 6

또는

In [14]:
x = d[2]/d[0]
x

6.0

앞서 정의한 `linear_eq` 함수를 이용하여 `y` 값을 계산한다.

In [15]:
y = linear_eq(1,12,4)
y

-8.0

### 2차원 어레이 활용 1차 연립방정식 풀기

아래 1차 연립방정식을 만족하는 `x, y` 구하기
```
a0*x + a1*y = a2
b0*x + b1*y = b2
```

행렬연산을 이용하여 다음과 같이 구할 수 있다.

$$A = \begin{pmatrix} a0 & a1 \\ b0 & b1 \end{pmatrix}$$

$$ A \cdot \begin{pmatrix} x \\ y \end{pmatrix} = \begin{pmatrix} a2 \\ b2 \end{pmatrix}$$

$$ \begin{pmatrix} x \\ y \end{pmatrix} = A^{-1}\cdot\begin{pmatrix} a2 \\ b2 \end{pmatrix}$$


In [16]:
A = np.array([[5,2], [2,1]])
print(A)

[[5 2]
 [2 1]]


In [17]:
np.linalg.inv(A)

array([[ 1., -2.],
       [-2.,  5.]])

In [18]:
np.matmul(np.linalg.inv(A),np.array([14,4]).T)

array([ 6., -8.])

In [19]:
# a, b가 리스트로 입력되는 것으로 기대

def simultaneous_eq(a,b):
    a_ = a[:2]
    b_ = b[:2]
    c_ = np.array([a[2], b[2]]).T
    A = np.array([a_, b_])
    A_inv = np.linalg.inv(A)
    return np.matmul(A_inv, c_)

In [20]:
a = [5,2,14]
b = [2,1,4]
simultaneous_eq(a,b)

array([ 6., -8.])

In [21]:
a = [2, 3, 4]   
b = [3, -4, -4]
simultaneous_eq(a,b)

array([0.23529412, 1.17647059])

In [22]:
a = [1,3,4]
b = [5,0,-10]
simultaneous_eq(a,b)

array([-2.,  2.])